apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse
      sources:
        direct: true
        # These are the default options and could be omitted
        autoPromotionOptions:
          selectionPolicy: NewestFreight
  # - origin:
  #     kind: Warehouse
  #     name: features
  #   sources:
  #     direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: dev-promote
          vars:
            - name: appName
              value: service-one
            - name: repoURL
              value: https://github.com/service-one
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/staging
            - name: argocdApp
              value: kargo-helm-staging

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
    - origin:
        kind: Warehouse
        name: features
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
